version: '3'

services:  
  server:
    build:
      context: .
    ports:
      - '3001:3001'
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: